---
- name: Configure NGINX for Taiga
  hosts: front
  become: yes
  become_user: root
  tasks:
    - name: Remove default NGINX config file
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create logs folder
      file:
        path: /home/logs
        state: directory

    - name: Create taiga.conf file
      copy:
        content: |
          server {
              listen 443 ssl;
              server_name 192.168.1.11;
              return 301 https://$server_name$request_uri;
              ssl_certificate     /tmp/mytrap.crt;
              ssl_certificate_key /tmp/mytrap.key;
          }

          server {
              listen 80;
              server_name 192.168.1.11;
              server_tokens off;
              
              ssl_certificate     /tmp/mytrap.crt;
              ssl_certificate_key /tmp/mytrap.key;
              ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
              ssl_ciphers         HIGH:!aNULL:!MD5;
              ssl_session_cache    shared:SSL:10m;  # ~ 40,000 sessions
              ssl_session_timeout  20m;
              ssl_prefer_server_ciphers on;
              
              large_client_header_buffers 4 32k;
              client_max_body_size 50M;
              charset utf-8;

              access_log /home/logs/nginx.access.log;
              error_log /home/logs/nginx.error.log;

              location / {
                  alias /home/taiga-front-dist/dist/;
                  index index.html;
                  try_files $uri $uri/ index.html =404;
              }

              location /api/ {
                  proxy_set_header Host $http_host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Scheme $scheme;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_pass http://192.168.1.10:8001/api/;
                  proxy_redirect off;
              }

              location /admin/ {
                  proxy_set_header Host $http_host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Scheme $scheme;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_pass http://192.168.1.10:8001/admin/;
                  proxy_redirect off;
              }

              location /static/ {
                  proxy_pass http://192.168.1.10:80;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }


             location /_protected/ {
                 proxy_pass http://192.168.1.10:80;
                 proxy_set_header Host $host;
                 proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-Proto $scheme;

              }

             location /media/exports/ {
                 proxy_pass http://192.168.1.10:80;
                 proxy_set_header Host $host;
                 proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-Proto $scheme;

              }

              location /media/ {
                  proxy_set_header Host $http_host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Scheme $scheme;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_pass http://192.168.1.10:8003/;
                  proxy_redirect off;
              }

              location /events {
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
                  proxy_connect_timeout 7d;
                  proxy_send_timeout 7d;
                  proxy_read_timeout 7d;
                  proxy_pass http://192.168.1.11/events;
              }
          }
        dest: /etc/nginx/conf.d/taiga.conf

