---
- name: Configure NGINX for Taiga
  hosts: backend
  become: yes
  become_user: root
  tasks:
    - name: Remove default NGINX config file
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create logs folder
      file:
        path: /home/logs
        state: directory

    - name: Create taiga.conf file
      copy:
        content: |
          server {
    listen 80 ssl;
    server_name 192.168.1.29;

                  ssl_certificate     /tmp/mytrap.crt;
                  ssl_certificate_key /tmp/mytrap.key;


    location / {
        proxy_pass http://192.168.1.29:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /_protected/ {
        internal;
        alias /home/taiga/taiga-back/media/;
        add_header Content-disposition "attachment";
    }

    location /media/ {
        alias /home/taiga/taiga-back/media/;
        add_header Content-disposition "attachment";
    }

    location /static/ {
        alias /home/taiga/taiga-back/static/;
        add_header Content-disposition "attachment";
    }
    
    location /frontend {
        proxy_pass http://192.168.1.30:443;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

        dest: /etc/nginx/conf.d/taiga.conf

